import Footer from "@/compoents/Footer";
import Navbar from "@/compoents/Navbar";
import HeroSection from "@/compoents/sections/HeroSection";
import ScrollSection from "@/compoents/sections/ScrollSection";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar />
        <HeroSection />
        <ScrollSection />
        <Footer />
      </main>
    </>
  );
}
